// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class Participant {
    "id": number;
    "fullName": string;
    "cipher": string;
    "schoolId": number;
    "className": string;
    "tasks": Task[];
    "createdAt": time$0.Time;

    /** Creates a new Participant instance. */
    constructor($$source: Partial<Participant> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("fullName" in $$source)) {
            this["fullName"] = "";
        }
        if (!("cipher" in $$source)) {
            this["cipher"] = "";
        }
        if (!("schoolId" in $$source)) {
            this["schoolId"] = 0;
        }
        if (!("className" in $$source)) {
            this["className"] = "";
        }
        if (!("tasks" in $$source)) {
            this["tasks"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Participant instance from a string or object.
     */
    static createFrom($$source: any = {}): Participant {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tasks" in $$parsedSource) {
            $$parsedSource["tasks"] = $$createField5_0($$parsedSource["tasks"]);
        }
        return new Participant($$parsedSource as Partial<Participant>);
    }
}

export class ParticipantReport {
    "id": number;
    "fullName": string;
    "cipher": string;
    "schoolId": number;
    "className": string;
    "tasks": Task[];
    "createdAt": time$0.Time;
    "total": number | null;
    "percent": number | null;
    "rating": string | null;
    "status": string | null;

    /** Creates a new ParticipantReport instance. */
    constructor($$source: Partial<ParticipantReport> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("fullName" in $$source)) {
            this["fullName"] = "";
        }
        if (!("cipher" in $$source)) {
            this["cipher"] = "";
        }
        if (!("schoolId" in $$source)) {
            this["schoolId"] = 0;
        }
        if (!("className" in $$source)) {
            this["className"] = "";
        }
        if (!("tasks" in $$source)) {
            this["tasks"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("total" in $$source)) {
            this["total"] = null;
        }
        if (!("percent" in $$source)) {
            this["percent"] = null;
        }
        if (!("rating" in $$source)) {
            this["rating"] = null;
        }
        if (!("status" in $$source)) {
            this["status"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ParticipantReport instance from a string or object.
     */
    static createFrom($$source: any = {}): ParticipantReport {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tasks" in $$parsedSource) {
            $$parsedSource["tasks"] = $$createField5_0($$parsedSource["tasks"]);
        }
        return new ParticipantReport($$parsedSource as Partial<ParticipantReport>);
    }
}

export class QuotaRule {
    "id": number;
    "minParticipants": number;
    "maxParticipants": number | null;
    "winnersQuota": number;
    "winnersAndPrizersQuota": number;
    "minWinnersPointsPercent": number;
    "createdAt": time$0.Time;

    /** Creates a new QuotaRule instance. */
    constructor($$source: Partial<QuotaRule> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("minParticipants" in $$source)) {
            this["minParticipants"] = 0;
        }
        if (!("maxParticipants" in $$source)) {
            this["maxParticipants"] = null;
        }
        if (!("winnersQuota" in $$source)) {
            this["winnersQuota"] = 0;
        }
        if (!("winnersAndPrizersQuota" in $$source)) {
            this["winnersAndPrizersQuota"] = 0;
        }
        if (!("minWinnersPointsPercent" in $$source)) {
            this["minWinnersPointsPercent"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuotaRule instance from a string or object.
     */
    static createFrom($$source: any = {}): QuotaRule {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuotaRule($$parsedSource as Partial<QuotaRule>);
    }
}

export class School {
    "value": number;
    "label": string;
    "createdAt": time$0.Time;

    /** Creates a new School instance. */
    constructor($$source: Partial<School> = {}) {
        if (!("value" in $$source)) {
            this["value"] = 0;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new School instance from a string or object.
     */
    static createFrom($$source: any = {}): School {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new School($$parsedSource as Partial<School>);
    }
}

export class Setting {
    "id": number;
    "name": string;
    "title": string;
    "value": string;
    "hidden": boolean;
    "createdAt": time$0.Time;

    /** Creates a new Setting instance. */
    constructor($$source: Partial<Setting> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("hidden" in $$source)) {
            this["hidden"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Setting instance from a string or object.
     */
    static createFrom($$source: any = {}): Setting {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Setting($$parsedSource as Partial<Setting>);
    }
}

export class Task {
    "id": number;
    "value": number;
    "number": number;
    "participantId": number;
    "createdAt": time$0.Time;

    /** Creates a new Task instance. */
    constructor($$source: Partial<Task> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("value" in $$source)) {
            this["value"] = 0;
        }
        if (!("number" in $$source)) {
            this["number"] = 0;
        }
        if (!("participantId" in $$source)) {
            this["participantId"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Task instance from a string or object.
     */
    static createFrom($$source: any = {}): Task {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Task($$parsedSource as Partial<Task>);
    }
}

// Private type creation functions
const $$createType0 = Task.createFrom;
const $$createType1 = $Create.Array($$createType0);
