// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Delete(entityName: string): $CancellablePromise<void> {
    return $Call.ByID(634177010, entityName);
}

export function Get(entityName: string): $CancellablePromise<any> {
    return $Call.ByID(423498975, entityName);
}

export function Save(entityName: string, entityID: number, payload: any): $CancellablePromise<$models.GenericBulkSaveResponse<any> | null> {
    return $Call.ByID(74895040, entityName, entityID, payload).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.GenericBulkSaveResponse.createFrom($Create.Any);
const $$createType1 = $Create.Nullable($$createType0);
