// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function ImportData(): $CancellablePromise<models$0.Participant[]> {
    return $Call.ByID(1967718016).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ImportDataFromFile(path: string): $CancellablePromise<models$0.Participant[]> {
    return $Call.ByID(444723110, path).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.Participant.createFrom;
const $$createType1 = $Create.Array($$createType0);
