// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Универсальный Payload для пакетного сохранения любой сущности
 */
export class GenericBulkSavePayload<T> {
    "create": T[];
    "update": T[];
    "delete": number[];

    /** Creates a new GenericBulkSavePayload instance. */
    constructor($$source: Partial<GenericBulkSavePayload<T>> = {}) {
        if (!("create" in $$source)) {
            this["create"] = [];
        }
        if (!("update" in $$source)) {
            this["update"] = [];
        }
        if (!("delete" in $$source)) {
            this["delete"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Given creation functions for each type parameter,
     * returns a creation function for a concrete instance
     * of the generic class GenericBulkSavePayload.
     */
    static createFrom<T = any>($$createParamT: (source: any) => T): ($$source?: any) => GenericBulkSavePayload<T> {
        const $$createField0_0 = $$createType0($$createParamT);
        const $$createField1_0 = $$createType0($$createParamT);
        const $$createField2_0 = $$createType1;
        return ($$source: any = {}) => {
            let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
            if ("create" in $$parsedSource) {
                $$parsedSource["create"] = $$createField0_0($$parsedSource["create"]);
            }
            if ("update" in $$parsedSource) {
                $$parsedSource["update"] = $$createField1_0($$parsedSource["update"]);
            }
            if ("delete" in $$parsedSource) {
                $$parsedSource["delete"] = $$createField2_0($$parsedSource["delete"]);
            }
            return new GenericBulkSavePayload<T>($$parsedSource as Partial<GenericBulkSavePayload<T>>);
        };
    }
}

/**
 * Универсальный ответ
 */
export class GenericBulkSaveResponse<T> {
    "success": boolean;
    "message": string;
    "data": T[];

    /** Creates a new GenericBulkSaveResponse instance. */
    constructor($$source: Partial<GenericBulkSaveResponse<T>> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Given creation functions for each type parameter,
     * returns a creation function for a concrete instance
     * of the generic class GenericBulkSaveResponse.
     */
    static createFrom<T = any>($$createParamT: (source: any) => T): ($$source?: any) => GenericBulkSaveResponse<T> {
        const $$createField2_0 = $$createType2($$createParamT);
        return ($$source: any = {}) => {
            let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
            if ("data" in $$parsedSource) {
                $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
            }
            return new GenericBulkSaveResponse<T>($$parsedSource as Partial<GenericBulkSaveResponse<T>>);
        };
    }
}

// Private type creation functions
const $$createType0 = ($$createParamT: any) => $Create.Array($$createParamT);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = ($$createParamT: any) => $Create.Array($$createParamT);
