// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function BulkSave(payload: $models.GenericBulkSavePayload<models$0.Participant>): $CancellablePromise<$models.GenericBulkSaveResponse<models$0.ParticipantReport> | null> {
    return $Call.ByID(231906994, payload).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Clear(): $CancellablePromise<void> {
    return $Call.ByID(3525946168);
}

/**
 * Delete удаляет запись по её ID.
 */
export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(2771787924, id);
}

/**
 * Get возвращает одну запись по её ID.
 */
export function Get(id: number): $CancellablePromise<models$0.Participant | null> {
    return $Call.ByID(2394960977, id).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetAll возвращает список всех записей.
 */
export function GetAll(): $CancellablePromise<models$0.ParticipantReport[]> {
    return $Call.ByID(1233342120).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * Update обновляет существующую запись в базе данных.
 */
export function Update(item: models$0.Participant | null): $CancellablePromise<void> {
    return $Call.ByID(730528438, item);
}

// Private type creation functions
const $$createType0 = models$0.ParticipantReport.createFrom;
const $$createType1 = $models.GenericBulkSaveResponse.createFrom($$createType0);
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = models$0.Participant.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType0);
