// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function BulkSave(payload: $models.GenericBulkSavePayload<models$0.QuotaRule>): $CancellablePromise<$models.GenericBulkSaveResponse<models$0.QuotaRule> | null> {
    return $Call.ByID(2852603617, payload).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetAll(): $CancellablePromise<models$0.QuotaRule[]> {
    return $Call.ByID(2365333519).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.QuotaRule.createFrom;
const $$createType1 = $models.GenericBulkSaveResponse.createFrom($$createType0);
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($$createType0);
