// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function BulkSave(payload: $models.GenericBulkSavePayload<models$0.School>): $CancellablePromise<$models.GenericBulkSaveResponse<models$0.School> | null> {
    return $Call.ByID(3799304361, payload).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Delete удаляет запись по её ID.
 */
export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(1103503403, id);
}

export function FindByTitle(title: string): $CancellablePromise<models$0.School | null> {
    return $Call.ByID(2099634464, title).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Get возвращает одну запись по её ID.
 */
export function Get(id: number): $CancellablePromise<models$0.School | null> {
    return $Call.ByID(3148130828, id).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetAll возвращает список всех записей.
 */
export function GetAll(): $CancellablePromise<models$0.School[]> {
    return $Call.ByID(131650263).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * Update обновляет существующую запись в базе данных.
 */
export function Update(item: models$0.School | null): $CancellablePromise<void> {
    return $Call.ByID(1076968177, item);
}

// Private type creation functions
const $$createType0 = models$0.School.createFrom;
const $$createType1 = $models.GenericBulkSaveResponse.createFrom($$createType0);
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Nullable($$createType0);
const $$createType4 = $Create.Array($$createType0);
