// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function BulkSave(payload: $models.GenericBulkSavePayload<models$0.Setting>): $CancellablePromise<$models.GenericBulkSaveResponse<models$0.Setting> | null> {
    return $Call.ByID(3640123344, payload).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Delete удаляет запись по её ID.
 */
export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(3413676394, id);
}

/**
 * Get возвращает одну запись по её ID.
 */
export function Get(id: number): $CancellablePromise<models$0.Setting | null> {
    return $Call.ByID(3312047095, id).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetAll(): $CancellablePromise<models$0.Setting[]> {
    return $Call.ByID(1134106802).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetAll возвращает список всех записей.
 */
export function GetAllDefaults(): $CancellablePromise<models$0.Setting[]> {
    return $Call.ByID(3535582852).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetAll возвращает список всех записей.
 */
export function GetAllVisible(): $CancellablePromise<models$0.Setting[]> {
    return $Call.ByID(3509477076).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetByName(name: string): $CancellablePromise<models$0.Setting | null> {
    return $Call.ByID(3058266057, name).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Update обновляет существующую запись в базе данных.
 */
export function Update(item: models$0.Setting | null): $CancellablePromise<void> {
    return $Call.ByID(3791893908, item);
}

// Private type creation functions
const $$createType0 = models$0.Setting.createFrom;
const $$createType1 = $models.GenericBulkSaveResponse.createFrom($$createType0);
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Nullable($$createType0);
const $$createType4 = $Create.Array($$createType0);
